import AppHeader from "@/components/AppHeader";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Database, MapPin, PackagePlus, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const emptyBlock = { id: undefined as number | undefined, name: "", colorHex: "#C8FF00", colorName: "ネオンライム", category: "壁", description: "" };

export default function Admin() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const adminData = trpc.catalog.adminData.useQuery(undefined, { enabled: user?.role === "admin" });
  const [block, setBlock] = useState(emptyBlock);
  const [blockMaterialsInput, setBlockMaterialsInput] = useState<Array<{ materialId: string; quantity: number }>>([{ materialId: "", quantity: 1 }]);
  const [materialName, setMaterialName] = useState("");
  const [materialLocation, setMaterialLocation] = useState<string>("");
  const [location, setLocation] = useState({ name: "", description: "", imageUrl: "" });
  const saveBlock = trpc.catalog.saveBlock.useMutation({ onSuccess: () => { toast.success("ブロックを登録しました"); setBlock(emptyBlock); setBlockMaterialsInput([{ materialId: "", quantity: 1 }]); utils.catalog.adminData.invalidate(); utils.catalog.list.invalidate(); } });
  const archiveBlock = trpc.catalog.archiveBlock.useMutation({ onSuccess: () => { toast.success("ブロックを非表示にしました"); utils.catalog.adminData.invalidate(); utils.catalog.list.invalidate(); } });
  const saveMaterial = trpc.catalog.saveMaterial.useMutation({ onSuccess: () => { toast.success("素材を登録しました"); setMaterialName(""); utils.catalog.adminData.invalidate(); } });
  const saveLocation = trpc.catalog.saveMiningLocation.useMutation({ onSuccess: () => { toast.success("採掘場所を登録しました"); setLocation({ name: "", description: "", imageUrl: "" }); utils.catalog.adminData.invalidate(); } });
  const editBlock = (id: number) => {
    const current = adminData.data?.blocks.find(item => item.id === id);
    if (!current) return;
    setBlock({ id: current.id, name: current.name, colorHex: current.colorHex, colorName: current.colorName, category: current.category, description: current.description ?? "" });
    const recipes = adminData.data?.recipes.filter(item => item.blockId === id) ?? [];
    setBlockMaterialsInput(recipes.length ? recipes.map(item => ({ materialId: String(item.materialId), quantity: item.quantity })) : [{ materialId: "", quantity: 1 }]);
    toast.message(`「${current.name}」の素材内訳を編集中です`);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  if (loading) return <div className="min-h-screen bg-[#090d20]" />;
  if (!user) return <AccessPanel title="管理画面にログイン" description="ブロックカタログの更新には管理者アカウントでのログインが必要です。" action={() => startLogin()} actionLabel="ログイン" />;
  if (user.role !== "admin") return <AccessPanel title="管理者権限が必要です" description="この画面は管理者に割り当てられたアカウントのみ利用できます。" />;

  return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold tracking-[0.18em] text-fuchsia-200"><ShieldCheck className="h-4 w-4" /> ADMIN CONSOLE</div><h1 className="font-pixel text-xl leading-relaxed text-[#f7f2d0]">カタログ管理</h1><p className="mt-3 text-sm text-slate-400">ブロック、素材、採掘場所の基礎データを更新します。</p></div><Badge className="w-fit border-fuchsia-400/30 bg-fuchsia-400/10 text-fuchsia-100">管理者：{user.name ?? "OWNER"}</Badge></div>
    <Tabs defaultValue="blocks" className="w-full"><TabsList className="h-auto flex-wrap justify-start gap-1 rounded-sm bg-[#111a36] p-1"><TabsTrigger value="blocks"><Database className="mr-2 h-4 w-4" />ブロック</TabsTrigger><TabsTrigger value="materials"><PackagePlus className="mr-2 h-4 w-4" />素材</TabsTrigger><TabsTrigger value="locations"><MapPin className="mr-2 h-4 w-4" />採掘場所</TabsTrigger></TabsList>
      <TabsContent value="blocks" className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={event => { event.preventDefault(); if (blockMaterialsInput.some(item => !item.materialId || item.quantity < 1)) { toast.error("すべての素材と必要数を入力してください"); return; } saveBlock.mutate({ ...block, materials: blockMaterialsInput.map(item => ({ materialId: Number(item.materialId), quantity: item.quantity })) }); }} className="pixel-panel p-5"><h2 className="flex items-center gap-2 font-pixel text-xs text-lime-200"><PackagePlus className="h-4 w-4" />ブロックを追加</h2><div className="mt-5 space-y-4"><Field label="ブロック名"><Input value={block.name} onChange={event => setBlock({ ...block, name: event.target.value })} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="カラーコード"><Input value={block.colorHex} onChange={event => setBlock({ ...block, colorHex: event.target.value })} required /></Field><Field label="色名"><Input value={block.colorName} onChange={event => setBlock({ ...block, colorName: event.target.value })} required /></Field></div><Field label="カテゴリ"><Input value={block.category} onChange={event => setBlock({ ...block, category: event.target.value })} required /></Field><div className="space-y-2"><Label className="text-xs text-slate-300">必要素材・必要数</Label>{blockMaterialsInput.map((row, index) => <div className="grid grid-cols-[1fr_72px_auto] gap-2" key={index}><Select value={row.materialId} onValueChange={materialId => setBlockMaterialsInput(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, materialId } : item))}><SelectTrigger><SelectValue placeholder="素材" /></SelectTrigger><SelectContent>{adminData.data?.materials.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select><Input aria-label="必要数" type="number" min="1" value={row.quantity} onChange={event => setBlockMaterialsInput(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, quantity: Math.max(1, Number(event.target.value)) } : item))} />{blockMaterialsInput.length > 1 ? <Button type="button" onClick={() => setBlockMaterialsInput(current => current.filter((_, itemIndex) => itemIndex !== index))} variant="ghost" size="sm" className="text-fuchsia-200 hover:bg-fuchsia-400/10 hover:text-fuchsia-100">削除</Button> : <span />}</div>)}<Button type="button" variant="outline" size="sm" onClick={() => setBlockMaterialsInput(current => [...current, { materialId: "", quantity: 1 }])} className="mt-2 border-cyan-300/35 text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50">素材内訳を追加</Button></div><Field label="説明"><Textarea value={block.description} onChange={event => setBlock({ ...block, description: event.target.value })} /></Field><Button disabled={saveBlock.isPending} className="pixel-button w-full bg-lime-300 text-[#090d20] hover:bg-lime-200">登録する</Button></div></form>
        <CatalogList loading={adminData.isLoading} blocks={adminData.data?.blocks ?? []} recipes={adminData.data?.recipes ?? []} onArchive={id => archiveBlock.mutate({ id })} onEdit={editBlock} /></TabsContent>
      <TabsContent value="materials" className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={event => { event.preventDefault(); saveMaterial.mutate({ name: materialName, miningLocationId: materialLocation ? Number(materialLocation) : null }); }} className="pixel-panel p-5"><h2 className="font-pixel text-xs text-cyan-200">素材を追加</h2><div className="mt-5 space-y-4"><Field label="素材名"><Input value={materialName} onChange={event => setMaterialName(event.target.value)} required /></Field><Field label="採掘場所"><Select value={materialLocation} onValueChange={setMaterialLocation}><SelectTrigger><SelectValue placeholder="未設定" /></SelectTrigger><SelectContent>{adminData.data?.locations.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Button disabled={saveMaterial.isPending} className="pixel-button w-full bg-cyan-300 text-[#090d20] hover:bg-cyan-200">素材を登録</Button></div></form><SimpleList icon={<PackagePlus className="h-4 w-4" />} title="登録済み素材" rows={adminData.data?.materials.map(item => ({ title: item.name, detail: item.description ?? "説明なし" })) ?? []} /></TabsContent>
      <TabsContent value="locations" className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={event => { event.preventDefault(); saveLocation.mutate({ name: location.name, description: location.description, imageUrl: location.imageUrl || null }); }} className="pixel-panel p-5"><h2 className="font-pixel text-xs text-yellow-200">採掘場所を追加</h2><div className="mt-5 space-y-4"><Field label="場所名"><Input value={location.name} onChange={event => setLocation({ ...location, name: event.target.value })} required /></Field><Field label="画像URL（任意）"><Input type="url" value={location.imageUrl} onChange={event => setLocation({ ...location, imageUrl: event.target.value })} placeholder="https://..." /></Field><Field label="説明"><Textarea value={location.description} onChange={event => setLocation({ ...location, description: event.target.value })} /></Field><Button disabled={saveLocation.isPending} className="pixel-button w-full bg-yellow-300 text-[#090d20] hover:bg-yellow-200">場所を登録</Button></div></form><SimpleList icon={<MapPin className="h-4 w-4" />} title="登録済み採掘場所" rows={adminData.data?.locations.map(item => ({ title: item.name, detail: item.description ?? "説明なし" })) ?? []} /></TabsContent>
    </Tabs>
  </main></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="text-xs text-slate-300">{label}</Label>{children}</div>; }
function AccessPanel({ title, description, action, actionLabel }: { title: string; description: string; action?: () => void; actionLabel?: string }) { return <div className="min-h-screen bg-[#090d20] px-4 py-16 text-slate-100"><div className="pixel-panel mx-auto max-w-lg p-8 text-center"><Wrench className="mx-auto h-9 w-9 text-fuchsia-300" /><h1 className="mt-5 font-pixel text-base leading-relaxed text-[#f7f2d0]">{title}</h1><p className="mt-4 text-sm leading-7 text-slate-300">{description}</p>{action && <Button onClick={action} className="pixel-button mt-6 bg-lime-300 text-[#090d20]">{actionLabel}</Button>}</div></div>; }
function CatalogList({ blocks, recipes, loading, onArchive, onEdit }: { blocks: Array<{ id: number; name: string; category: string; colorName: string; colorHex: string; isActive: boolean }>; recipes: Array<{ blockId: number; materialId: number; materialName: string; quantity: number }>; loading: boolean; onArchive: (id: number) => void; onEdit: (id: number) => void }) { return <section className="pixel-panel p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-pixel text-xs text-fuchsia-200">登録済みブロック</h2><span className="text-xs text-slate-400">{loading ? "…" : `${blocks.length}件`}</span></div><div className="max-h-[580px] space-y-2 overflow-y-auto pr-1">{blocks.map(item => { const itemRecipes = recipes.filter(recipe => recipe.blockId === item.id); return <div key={item.id} className="border border-white/10 bg-[#0b122b] p-3"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="h-7 w-7 shrink-0 border border-white/20" style={{ background: item.colorHex }} /><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-100">{item.name}</p><p className="text-xs text-slate-400">{item.category} / {item.colorName}</p></div></div><div className="flex shrink-0 gap-1"><Button onClick={() => onEdit(item.id)} variant="ghost" size="sm" className="text-xs text-cyan-200 hover:bg-cyan-300/10 hover:text-cyan-100">内訳を編集</Button>{item.isActive ? <Button onClick={() => onArchive(item.id)} variant="ghost" size="sm" className="text-xs text-slate-400 hover:bg-fuchsia-400/10 hover:text-fuchsia-200">非表示</Button> : <Badge variant="outline" className="border-white/10 text-slate-500">非表示</Badge>}</div></div><p className="mt-2 border-t border-white/10 pt-2 text-[11px] text-slate-400">素材内訳：{itemRecipes.length ? itemRecipes.map(recipe => `${recipe.materialName} × ${recipe.quantity}`).join(" / ") : "未登録"}</p></div>; })}</div></section>; }
function SimpleList({ icon, title, rows }: { icon: React.ReactNode; title: string; rows: Array<{ title: string; detail: string }> }) { return <section className="pixel-panel p-5"><h2 className="mb-4 flex items-center gap-2 font-pixel text-xs text-slate-100">{icon}{title}</h2><div className="space-y-2">{rows.map(row => <div key={row.title} className="border border-white/10 bg-[#0b122b] p-3"><p className="text-sm font-bold text-slate-100">{row.title}</p><p className="mt-1 text-xs text-slate-400">{row.detail}</p></div>)}</div></section>; }
