import AppHeader from "@/components/AppHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { ReferenceGallery } from "@/components/ReferenceGallery";
import { AlertTriangle, ArrowLeft, CheckCircle2, CircleAlert, FileImage, Grid2X2, Layers3, Palette, Rotate3D, ScanSearch, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";

type Analysis = {
  summary: string;
  suitability: { overallScore: number; verdict: string; backgroundScore: number; resolutionScore: number; partVisibilityScore: number; depthScore: number };
  assessments: Array<{ criterion: string; score: number; status: "good" | "caution" | "poor"; note: string }>;
  parts: Array<{ id: string; name: string; role: string; layerId: string; dominantColor: string; coveragePercent: number; visibility: string; notes: string }>;
  layers: Array<{ id: string; name: string; order: number; purpose: string }>;
  colorPalette: Array<{ name: string; hex: string; prominence: number }>;
  cautions: string[];
};

export default function ProjectAnalysis() {
  const [, params] = useRoute("/workspace/:id");
  const projectId = Number(params?.id ?? 0);
  const project = trpc.projects.get.useQuery({ id: projectId }, { enabled: projectId > 0 });
  if (project.isLoading) return <div className="min-h-screen bg-[#090d20]" />;
  if (project.isError || !project.data) return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><div className="pixel-panel mx-auto mt-20 max-w-lg p-8 text-center"><CircleAlert className="mx-auto h-8 w-8 text-fuchsia-200" /><h1 className="mt-4 font-pixel text-sm leading-relaxed text-[#f7f2d0]">プロジェクトを開けません</h1><p className="mt-3 text-sm text-slate-400">{project.error?.message ?? "対象のプロジェクトが見つかりません。"}</p><Link href="/workspace"><Button className="mt-5 bg-lime-300 text-[#090d20]">新しい解析をはじめる</Button></Link></div></div>;
  const analysis = project.data.analysis as Analysis | null;
  if (!analysis) return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><div className="mx-auto max-w-4xl px-4 py-16"><p>解析結果を準備しています。</p></div></div>;
  const scoreItems = [["背景", analysis.suitability.backgroundScore], ["解像度", analysis.suitability.resolutionScore], ["部位欠損", analysis.suitability.partVisibilityScore], ["立体構造", analysis.suitability.depthScore]];
  return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8"><Link href="/workspace" className="inline-flex items-center text-xs font-bold text-cyan-200 no-underline hover:text-cyan-50"><ArrowLeft className="mr-2 h-4 w-4" />新しい資料を解析</Link><div className="mt-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold tracking-[.18em] text-lime-200">ANALYSIS COMPLETE</p><h1 className="mt-3 font-pixel text-lg leading-relaxed text-[#f7f2d0]">{project.data.title}</h1><p className="mt-3 text-sm text-slate-400">高さ {project.data.buildingHeight} blocks / 解析済みの建築資料</p></div><Link href={`/workspace/${projectId}/design`}><Button className="pixel-button bg-lime-300 text-[#090d20] hover:bg-lime-200">ブロック候補を選ぶ <ArrowLeft className="ml-2 h-4 w-4 rotate-180" /></Button></Link></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[.82fr_1.18fr]"><section className="space-y-5"><ReferenceGallery projectId={projectId} sourceImageUrl={project.data.sourceImageUrl} references={project.data.references} onUpdated={() => project.refetch()} /><div className="pixel-panel overflow-hidden p-3">{project.data.sourceImageUrl ? <img src={project.data.sourceImageUrl} alt="保存した建築資料" className="max-h-[540px] w-full object-contain" /> : <div className="grid h-80 place-items-center text-slate-500">画像なし</div>}</div><section className="border border-fuchsia-400/25 bg-fuchsia-400/5 p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-[.15em] text-fuchsia-200"><AlertTriangle className="h-4 w-4" />注意点</div><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-300">{analysis.cautions.length ? analysis.cautions.map(note => <li key={note}>・{note}</li>) : <li>・大きな注意点は検出されませんでした。</li>}</ul></section></section>
      <section className="space-y-5"><div className="pixel-panel p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-cyan-200">BUILDING SUITABILITY</p><h2 className="mt-3 font-pixel text-sm leading-relaxed text-[#f7f2d0]">建築適性スコア</h2></div><div className="grid h-24 w-24 place-items-center border-4 border-lime-300 bg-lime-300/10"><span className="font-pixel text-2xl text-lime-300">{analysis.suitability.overallScore}</span></div></div><p className="mt-4 text-sm leading-7 text-slate-300">{analysis.summary}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{scoreItems.map(([label, score]) => <div key={String(label)} className="border border-white/10 bg-[#090d20] p-3"><div className="flex justify-between text-xs"><span className="text-slate-400">{label}</span><span className="font-pixel text-lime-300">{score}</span></div><Progress value={Number(score)} className="mt-3 h-2 bg-white/10 [&>div]:bg-cyan-300" /></div>)}</div></div>
        <div className="grid gap-5 lg:grid-cols-2"><section className="border border-white/10 bg-[#111a36] p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-[.15em] text-cyan-200"><ScanSearch className="h-4 w-4" />評価詳細</div><div className="mt-4 space-y-3">{analysis.assessments.map(item => <div key={item.criterion} className="border-b border-white/10 pb-3 last:border-0"><div className="flex justify-between gap-3"><p className="text-sm font-bold text-slate-100">{item.criterion}</p><span className={item.status === "good" ? "font-pixel text-[10px] text-lime-300" : "font-pixel text-[10px] text-yellow-200"}>{item.score}</span></div><p className="mt-1 text-xs leading-5 text-slate-400">{item.note}</p></div>)}</div></section><section className="border border-white/10 bg-[#111a36] p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-[.15em] text-fuchsia-200"><Palette className="h-4 w-4" />検出カラー</div><div className="mt-5 grid grid-cols-2 gap-3">{analysis.colorPalette.map(color => <div key={`${color.name}-${color.hex}`} className="flex items-center gap-3"><span className="h-8 w-8 border border-white/20" style={{ background: color.hex }} /><div><p className="text-xs font-bold text-slate-100">{color.name}</p><p className="text-[10px] text-slate-500">{color.hex}</p></div></div>)}</div></section></div>
        <section className="pixel-panel p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-[.15em] text-yellow-100"><Layers3 className="h-4 w-4" />建築レイヤー</div><div className="mt-5 space-y-3">{analysis.layers.sort((a, b) => a.order - b.order).map(layer => <div key={layer.id} className="flex gap-4 border border-white/10 bg-[#090d20] p-3"><span className="grid h-8 w-8 shrink-0 place-items-center border border-yellow-300/30 bg-yellow-300/10 font-pixel text-[10px] text-yellow-200">{layer.order}</span><div><h3 className="text-sm font-bold text-slate-100">{layer.name}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{layer.purpose}</p></div></div>)}</div></section>
        {(project.data.blueprint2dImageUrl || project.data.blueprint3dImageUrl) && <section className="pixel-panel p-5"><div className="flex items-center gap-2 text-xs font-bold tracking-[.15em] text-cyan-200"><FileImage className="h-4 w-4" />保存済み設計図</div><p className="mt-3 text-xs leading-5 text-slate-400">設計スタジオで出力した設計図をこの画面でも確認できます。画像を選ぶと元のPNGを開きます。</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{project.data.blueprint2dImageUrl && <a href={project.data.blueprint2dImageUrl} target="_blank" rel="noreferrer" className="group overflow-hidden border border-cyan-300/30 bg-[#090d20] no-underline"><img src={project.data.blueprint2dImageUrl} alt="保存済み2D設計図" className="aspect-square w-full object-contain bg-[#090d20]" /><div className="border-t border-cyan-300/20 p-3"><div className="flex items-center gap-2"><Grid2X2 className="h-5 w-5 text-cyan-200" /><p className="text-xs font-bold text-slate-100">2D設計図PNG</p></div><p className="mt-1 text-[10px] text-slate-500">クリックして拡大表示</p></div></a>}{project.data.blueprint3dImageUrl && <a href={project.data.blueprint3dImageUrl} target="_blank" rel="noreferrer" className="group overflow-hidden border border-fuchsia-300/30 bg-[#090d20] no-underline"><img src={project.data.blueprint3dImageUrl} alt="保存済み3Dプレビュー" className="aspect-square w-full object-contain bg-[#090d20]" /><div className="border-t border-fuchsia-300/20 p-3"><div className="flex items-center gap-2"><Rotate3D className="h-5 w-5 text-fuchsia-200" /><p className="text-xs font-bold text-slate-100">3DプレビューPNG</p></div><p className="mt-1 text-[10px] text-slate-500">クリックして拡大表示</p></div></a>}</div></section>}
      </section></div>
  </main></div>;
}
