import AppHeader from "@/components/AppHeader";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowRight, CircleAlert, FileImage, FolderOpen, Grid2X2, Plus, Rotate3D } from "lucide-react";
import { Link } from "wouter";

const labels = { draft: "作成中", analyzed: "解析済み", designed: "設計済み" } as const;

export default function Projects() {
  const { user, loading } = useAuth();
  const projects = trpc.projects.list.useQuery(undefined, { enabled: Boolean(user) });
  if (loading) return <div className="min-h-screen bg-[#090d20]" />;
  if (!user) return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><div className="pixel-panel mx-auto mt-20 max-w-lg p-8 text-center"><FolderOpen className="mx-auto h-9 w-9 text-cyan-200" /><h1 className="mt-5 font-pixel text-sm leading-relaxed text-[#f7f2d0]">保存プロジェクト</h1><p className="mt-4 text-sm leading-7 text-slate-300">解析結果と設計図を再利用するにはログインしてください。</p><Button onClick={() => startLogin()} className="pixel-button mt-6 bg-lime-300 text-[#090d20]">ログインする</Button></div></div>;
  return <div className="min-h-screen bg-[#090d20] text-slate-100"><AppHeader /><main className="mx-auto max-w-[1440px] px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.18em] text-cyan-200">SAVED PROJECTS</p><h1 className="mt-3 font-pixel text-lg leading-relaxed text-[#f7f2d0]">保存プロジェクト</h1><p className="mt-3 text-sm text-slate-400">入力資料、サイズ、選択ブロック、設計図、PNG出力をいつでも開き直せます。</p></div><Link href="/workspace"><Button className="pixel-button bg-lime-300 text-[#090d20] hover:bg-lime-200"><Plus className="mr-2 h-4 w-4" />新しい解析</Button></Link></div>
    {projects.isError ? <div className="mt-8 border border-fuchsia-400/30 bg-fuchsia-400/10 p-8 text-center"><CircleAlert className="mx-auto h-7 w-7 text-fuchsia-200" /><p className="mt-3 text-sm text-slate-200">プロジェクトを取得できませんでした。</p><Button onClick={() => projects.refetch()} className="mt-4 bg-fuchsia-300 text-[#090d20]">再試行</Button></div> : projects.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="h-72 animate-pulse border border-white/10 bg-[#111a36]" />)}</div> : projects.data?.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.data.map(project => <article key={project.id} className="block-card overflow-hidden"><div className="grid h-40 place-items-center bg-[#111a36]">{project.sourceImageUrl ? <img src={project.sourceImageUrl} alt={`${project.title}の参照資料`} className="h-full w-full object-cover" /> : <FileImage className="h-9 w-9 text-slate-600" />}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="line-clamp-2 text-base font-bold text-slate-100">{project.title}</h2><Badge className={project.status === "designed" ? "border-lime-300/30 bg-lime-300/10 text-lime-200" : "border-cyan-300/30 bg-cyan-300/10 text-cyan-100"}>{labels[project.status]}</Badge></div><p className="mt-2 text-xs text-slate-500">高さ {project.buildingHeight} blocks / 更新 {new Date(project.updatedAt).toLocaleDateString("ja-JP")}</p><div className="mt-5 flex gap-2"><Link href={`/workspace/${project.id}`}><Button variant="outline" size="sm" className="border-cyan-300/35 text-cyan-100 hover:bg-cyan-300/10 hover:text-cyan-50">解析を見る</Button></Link><Link href={`/workspace/${project.id}/design`}><Button size="sm" className="bg-lime-300 text-[#090d20] hover:bg-lime-200">設計を開く <ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></Link></div></div></article>)}</div> : <div className="pixel-panel mt-8 p-12 text-center"><Archive className="mx-auto h-10 w-10 text-cyan-200" /><h2 className="mt-5 font-pixel text-sm leading-relaxed text-[#f7f2d0]">まだプロジェクトがありません</h2><p className="mt-3 text-sm leading-7 text-slate-400">最初の画像をアップロードして、建築資料を解析しましょう。</p><Link href="/workspace"><Button className="pixel-button mt-6 bg-lime-300 text-[#090d20]">画像を解析する</Button></Link></div>}
  </main></div>;
}
