import { and, eq, inArray, isNull, or } from "drizzle-orm";
import { getDb, memStore } from "./db";
import { blockMaterials, blocks, materials, miningLocations, projectSelections } from "../drizzle/schema";

const starterLocations = [
  { name: "月影鉱山", description: "石材・岩片を採掘できる深い坑道。" },
  { name: "ひかりの森", description: "木材と植物由来の素材を集められる森林地帯。" },
  { name: "プリズム洞窟", description: "結晶片と希少な発光素材が見つかる洞窟。" },
  { name: "きらめき海岸", description: "砂・貝殻・水辺の素材を収集できる海岸。" },
];

const starterMaterials = [
  { name: "石材", location: "月影鉱山", description: "壁と石ブロックの基礎素材。" },
  { name: "岩片", location: "月影鉱山", description: "道路や舗装に向く加工前の岩片。" },
  { name: "木材", location: "ひかりの森", description: "床・梁・装飾に使う基本の木材。" },
  { name: "結晶片", location: "プリズム洞窟", description: "発光装飾を作るための結晶素材。" },
  { name: "砂", location: "きらめき海岸", description: "砂岩系ブロックに加工できる粒状素材。" },
];

export const specialCatalogBlocks = [
  // --- 初期28種 ---
  {
    name: "あおいわ",
    colorHex: "#3B82F6",
    colorName: "シアン",
    category: "石",
    description: "鮮やかな青色を帯びた自然岩ブロック。月影鉱山の青岩層で採掘される。",
    imageUrl: "/blocks/aoiwa.svg",
    material: "石材",
  },
  {
    name: "あおどうくついわ",
    colorHex: "#2563EB",
    colorName: "ネイビー",
    category: "石",
    description: "洞窟深層部で採掘される層状の青い岩石ブロック。",
    imageUrl: "/blocks/aodoukutusiwa.svg",
    material: "石材",
  },
  {
    name: "あらふるうろこ",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "装飾",
    description: "水棲生物の鱗を模した青・緑・橙の波状装飾タイル。",
    imageUrl: "/blocks/arafuruuroko.svg",
    material: "結晶片",
  },
  {
    name: "あらふるさんご",
    colorHex: "#F472B6",
    colorName: "マゼンタ",
    category: "装飾",
    description: "鮮やかな珊瑚や熱帯植物の模様が散りばめられた装飾ブロック。",
    imageUrl: "/blocks/arafurusango.svg",
    material: "砂",
  },
  {
    name: "いしこし",
    colorHex: "#E2E8F0",
    colorName: "グレー",
    category: "壁",
    description: "額縁状のレリーフが彫り込まれた精巧な切石壁ブロック。",
    imageUrl: "/blocks/ishikoshi.svg",
    material: "石材",
  },
  {
    name: "いろどりつるつるたいる",
    colorHex: "#C084FC",
    colorName: "マゼンタ",
    category: "床",
    description: "光沢のあるパステルカラー4色が組み合わさった滑らかタイル。",
    imageUrl: "/blocks/irodoritsurutsurutairu.svg",
    material: "岩片",
  },
  {
    name: "うみこけつち",
    colorHex: "#F43F5E",
    colorName: "マゼンタ",
    category: "床",
    description: "海辺の苔や特殊な胞子が付着したピンク色の土ブロック。",
    imageUrl: "/blocks/umikoketsuchi.svg",
    material: "砂",
  },
  {
    name: "うるしぬりかべ",
    colorHex: "#B91C1C",
    colorName: "マゼンタ",
    category: "壁",
    description: "艶やかな漆塗りの光沢と深みのある赤が特徴の和風壁ブロック。",
    imageUrl: "/blocks/urushinurikabe.svg",
    material: "木材",
  },
  {
    name: "おうぎめたもん",
    colorHex: "#A855F7",
    colorName: "マゼンタ",
    category: "装飾",
    description: "雅な扇の幾何学模様が連続して刻まれた伝統的な装飾壁。",
    imageUrl: "/blocks/ougimetamon.svg",
    material: "結晶片",
  },
  {
    name: "おごそかなかべうえした",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "壁",
    description: "ハート型と唐草の優美なレリーフが彫られた宮殿用壁ブロック。",
    imageUrl: "/blocks/ogosokanokabe_ueshita.svg",
    material: "石材",
  },
  {
    name: "おごそかなかべまんなか",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "壁",
    description: "ダイヤ型の彫刻が入った格式高い大理石調の壁ブロック。",
    imageUrl: "/blocks/ogosokanokabe_mannaka.svg",
    material: "石材",
  },
  {
    name: "おごそかなゆか",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "床",
    description: "金色の装飾帯とクロス文様が施された神殿風の床ブロック。",
    imageUrl: "/blocks/ogosokanayuka.svg",
    material: "石材",
  },
  {
    name: "おりえんたる",
    colorHex: "#7F1D1D",
    colorName: "マゼンタ",
    category: "壁",
    description: "ダークウッドにエメラルドグリーンの格子枠が映える東洋風壁。",
    imageUrl: "/blocks/orientaru.svg",
    material: "木材",
  },
  {
    name: "かいていのも",
    colorHex: "#0EA5E9",
    colorName: "シアン",
    category: "道路",
    description: "砂地の上に鮮やかな海藻が茂った海底風の自然ブロック。",
    imageUrl: "/blocks/kaiteinomo.svg",
    material: "砂",
  },
  {
    name: "かさなりなみもよう",
    colorHex: "#60A5FA",
    colorName: "シアン",
    category: "装飾",
    description: "波が幾重にも重なる爽やかな青の装飾タイル。",
    imageUrl: "/blocks/kasanarinamimoyou.svg",
    material: "岩片",
  },
  {
    name: "からふるいかり",
    colorHex: "#4338CA",
    colorName: "ネイビー",
    category: "装飾",
    description: "紺碧の地にオレンジとシアンの碇が描かれたマリン調ブロック。",
    imageUrl: "/blocks/karafuruikari.svg",
    material: "岩片",
  },
  {
    name: "ぐらでうえ",
    colorHex: "#FB7185",
    colorName: "マゼンタ",
    category: "壁",
    description: "天面が濃いピンクで下部に向かって白く変化するグラデーション壁。",
    imageUrl: "/blocks/guradeue.svg",
    material: "石材",
  },
  {
    name: "ぐらでした",
    colorHex: "#FDA4AF",
    colorName: "ホワイト",
    category: "壁",
    description: "天面が白く下部に向かってピンクが濃くなるグラデーション壁。",
    imageUrl: "/blocks/guradeshita.svg",
    material: "石材",
  },
  {
    name: "さんごのもり",
    colorHex: "#FBCFE8",
    colorName: "マゼンタ",
    category: "装飾",
    description: "珊瑚と海草がぎっしり詰まった淡いパステル調の海底ブロック。",
    imageUrl: "/blocks/sangonomori.svg",
    material: "砂",
  },
  {
    name: "しっくないかり",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "壁",
    description: "白漆喰に舵輪と碇のエッチングが施されたアンティーク調ブロック。",
    imageUrl: "/blocks/shikkunaikari.svg",
    material: "石材",
  },
  {
    name: "しましまなみもよう",
    colorHex: "#2DD4BF",
    colorName: "ライム",
    category: "装飾",
    description: "爽やかなミントグリーンの波型ストライプが描かれた装飾タイル。",
    imageUrl: "/blocks/shimashimanamimoyou.svg",
    material: "岩片",
  },
  {
    name: "つーとん",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "壁",
    description: "上部が水色、下部がサーモンピンクにきれいに分かれたブロック。",
    imageUrl: "/blocks/tsuton.svg",
    material: "石材",
  },
  {
    name: "つるつるたいる",
    colorHex: "#BAE6FD",
    colorName: "シアン",
    category: "床",
    description: "4分割の目地が入った清潔感あふれる水色の光沢タイル。",
    imageUrl: "/blocks/tsurutsurutairu.svg",
    material: "岩片",
  },
  {
    name: "でじたる",
    colorHex: "#06B6D4",
    colorName: "シアン",
    category: "装飾",
    description: "電子回路とネオングリッドが発光するサイバーテックブロック。",
    imageUrl: "/blocks/dejitaru.svg",
    material: "結晶片",
  },
  {
    name: "ぶろっくうき",
    colorHex: "#0284C7",
    colorName: "シアン",
    category: "道路",
    description: "表面に整然とした丸いスタッド突起が並ぶ機能性ブロック。",
    imageUrl: "/blocks/burokkuuki.svg",
    material: "岩片",
  },
  {
    name: "ほしつぶいわ",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "石",
    description: "星屑のようなきらめく結晶と青いラインを含む神秘的な鉱石岩。",
    imageUrl: "/blocks/hoshitsubuiwa.svg",
    material: "結晶片",
  },
  {
    name: "めたる",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "壁",
    description: "ボルト留めされた頑丈な鋼鉄パネルのインダストリアルブロック。",
    imageUrl: "/blocks/metaru.svg",
    material: "石材",
  },
  {
    name: "よこながしかく",
    colorHex: "#E0F2FE",
    colorName: "シアン",
    category: "壁",
    description: "横長のレンガ目地が刻まれたスタイリッシュな水色壁タイル。",
    imageUrl: "/blocks/yokonagashikaku.svg",
    material: "石材",
  },

  // --- 提供ブロック第1弾 (43種) ---
  {
    name: "アーガイルチェック",
    colorHex: "#DC2626",
    colorName: "レッド",
    category: "装飾",
    description: "赤地にホワイトとゴールドの菱形が交差するアーガイルチェック柄ブロック。",
    imageUrl: "/blocks/argyle_check.svg",
    material: "木材",
  },
  {
    name: "アーチタイル",
    colorHex: "#E07A5F",
    colorName: "オレンジ",
    category: "床",
    description: "優美なアーチ状の扇形目地が刻まれたテラコッタ調タイル。",
    imageUrl: "/blocks/arch_tile.svg",
    material: "石材",
  },
  {
    name: "あかいけずれたいわ",
    colorHex: "#9C5146",
    colorName: "ブラウン",
    category: "石",
    description: "階段状に段差が削り出された赤岩ブロック。",
    imageUrl: "/blocks/akai_kezuretaiwa.svg",
    material: "岩片",
  },
  {
    name: "あかいツブがけいわ",
    colorHex: "#E89A7A",
    colorName: "オレンジ",
    category: "石",
    description: "上下に薄茶色の地層を持ち、中央に赤粒が詰まった崖岩。",
    imageUrl: "/blocks/akai_tsubugakeiwa.svg",
    material: "砂",
  },
  {
    name: "あかいわ",
    colorHex: "#A05544",
    colorName: "ブラウン",
    category: "石",
    description: "赤みを帯びた重厚な自然岩石ブロック。",
    imageUrl: "/blocks/akaiwa.svg",
    material: "石材",
  },
  {
    name: "あかがけいわ",
    colorHex: "#E67E50",
    colorName: "オレンジ",
    category: "石",
    description: "赤土と砂岩が層をなす鮮やかな断崖の岩石。",
    imageUrl: "/blocks/akagakeiwa.svg",
    material: "砂",
  },
  {
    name: "あかちゃどうくついわ",
    colorHex: "#8B5244",
    colorName: "ブラウン",
    category: "石",
    description: "赤茶とダークブラウンの水平地層が重なる洞窟深層の岩石。",
    imageUrl: "/blocks/akacha_doukutusiwa.svg",
    material: "石材",
  },
  {
    name: "アスファルトのみち",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "道路",
    description: "天面がダークグレーに舗装された滑らかなアスファルト道路ブロック。",
    imageUrl: "/blocks/asphalt_no_michi.svg",
    material: "岩片",
  },
  {
    name: "アンティークなカベ・うえ",
    colorHex: "#C28834",
    colorName: "ブラウン",
    category: "壁",
    description: "上部に唐草風の飾り彫刻が施された高級感のあるアンティーク木製壁。",
    imageUrl: "/blocks/antique_kabe_ue.svg",
    material: "木材",
  },
  {
    name: "アンティークなカベ・した",
    colorHex: "#B87A28",
    colorName: "ブラウン",
    category: "壁",
    description: "下部に重厚な額縁パネルが組まれたアンティーク木製壁の土台部。",
    imageUrl: "/blocks/antique_kabe_shita.svg",
    material: "木材",
  },
  {
    name: "アンティークなカベ・なか",
    colorHex: "#BF8230",
    colorName: "ブラウン",
    category: "壁",
    description: "中央に華麗な植物レリーフが彫り込まれたアンティーク木製壁。",
    imageUrl: "/blocks/antique_kabe_naka.svg",
    material: "木材",
  },
  {
    name: "いえのどだい",
    colorHex: "#F59E0B",
    colorName: "イエロー",
    category: "壁",
    description: "上部が暖かみのあるベージュ、下部がグレーのツートンカラーの家の土台ブロック。",
    imageUrl: "/blocks/ie_no_dodai.svg",
    material: "石材",
  },
  {
    name: "いしづみのカベ",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "壁",
    description: "丸みを帯びた自然石を緻密に積み上げた石垣壁ブロック。",
    imageUrl: "/blocks/ishizumi_no_kabe.svg",
    material: "石材",
  },
  {
    name: "いしのタイル",
    colorHex: "#CBD5E1",
    colorName: "グレー",
    category: "床",
    description: "方形に整然と切り出された滑らかな石造りタイル。",
    imageUrl: "/blocks/ishi_no_tile.svg",
    material: "石材",
  },
  {
    name: "いしのはしら・うえ",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "壁",
    description: "上部に飾り段差を持つ白大理石風の石柱トップブロック。",
    imageUrl: "/blocks/ishi_no_hashira_ue.svg",
    material: "石材",
  },
  {
    name: "いしのはしら・した",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "壁",
    description: "下部にベース段差を持つ白大理石風の石柱ベースブロック。",
    imageUrl: "/blocks/ishi_no_hashira_shita.svg",
    material: "石材",
  },
  {
    name: "いしのはしら・まんなか",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "壁",
    description: "中央に溝線が刻まれた白大理石風の石柱中間ブロック。",
    imageUrl: "/blocks/ishi_no_hashira_mannaka.svg",
    material: "石材",
  },
  {
    name: "いしのゆか",
    colorHex: "#E2E8F0",
    colorName: "グレー",
    category: "床",
    description: "シンプルでどんな建築にも馴染むフラットな石床ブロック。",
    imageUrl: "/blocks/ishi_no_yuka.svg",
    material: "石材",
  },
  {
    name: "いしラインのゆか",
    colorHex: "#CBD5E1",
    colorName: "グレー",
    category: "床",
    description: "中央に縦の溝ラインが走るアクセント用の石床ブロック。",
    imageUrl: "/blocks/ishi_line_no_yuka.svg",
    material: "石材",
  },
  {
    name: "いしレンガのカベ",
    colorHex: "#E2E8F0",
    colorName: "グレー",
    category: "壁",
    description: "明るい石材をレンガ状に組んだ上品な壁ブロック。",
    imageUrl: "/blocks/ishi_renga_no_kabe.svg",
    material: "石材",
  },
  {
    name: "うきしまのがけいわ",
    colorHex: "#E5C578",
    colorName: "イエロー",
    category: "石",
    description: "浮島地帯の明るい黄色みを帯びた砂岩質の崖ブロック。",
    imageUrl: "/blocks/ukishima_no_gakeiwa.svg",
    material: "砂",
  },
  {
    name: "うきしまのすな",
    colorHex: "#F1DE9E",
    colorName: "イエロー",
    category: "床",
    description: "浮島特有のきめ細やかな黄金色の砂ブロック。",
    imageUrl: "/blocks/ukishima_no_suna.svg",
    material: "砂",
  },
  {
    name: "うきしまのすないわ",
    colorHex: "#EAD28B",
    colorName: "イエロー",
    category: "石",
    description: "浮島の砂が固まってできた風合いのある砂岩ブロック。",
    imageUrl: "/blocks/ukishima_no_sunaiwa.svg",
    material: "砂",
  },
  {
    name: "うきしまのツブがけいわ",
    colorHex: "#E8CE84",
    colorName: "イエロー",
    category: "石",
    description: "浮島の砂岩層に大小の小石・粒子が混ざり合った崖岩ブロック。",
    imageUrl: "/blocks/ukishima_no_tsubugakeiwa.svg",
    material: "砂",
  },
  {
    name: "うすちゃいわ",
    colorHex: "#D97746",
    colorName: "オレンジ",
    category: "石",
    description: "素朴で温かみのある薄茶色の自然岩石ブロック。",
    imageUrl: "/blocks/usucha_iwa.svg",
    material: "石材",
  },
  {
    name: "うすちゃのけずれたいわ",
    colorHex: "#D47C4B",
    colorName: "オレンジ",
    category: "石",
    description: "階段状にカットされた薄茶色の岩石ブロック。",
    imageUrl: "/blocks/usucha_no_kezuretaiwa.svg",
    material: "岩片",
  },
  {
    name: "うちっぱなしのカベ",
    colorHex: "#E2E8F0",
    colorName: "グレー",
    category: "壁",
    description: "四隅にセパレーター穴のあるモダンなコンクリート打ちっぱなし壁。",
    imageUrl: "/blocks/uchippanashi_no_kabe.svg",
    material: "石材",
  },
  {
    name: "うみのいわ",
    colorHex: "#8B7BA8",
    colorName: "ネイビー",
    category: "石",
    description: "紫と金色の繊細な層を持つ神秘的な海底岩石ブロック。",
    imageUrl: "/blocks/umi_no_iwa.svg",
    material: "結晶片",
  },
  {
    name: "うみべのすな",
    colorHex: "#F8F3DC",
    colorName: "ホワイト",
    category: "床",
    description: "波打ち際の白くサラサラとした美しい砂浜ブロック。",
    imageUrl: "/blocks/umibe_no_suna.svg",
    material: "砂",
  },
  {
    name: "うろこタイル",
    colorHex: "#DDD6FE",
    colorName: "ホワイト",
    category: "床",
    description: "淡い紫色の鱗模様が連なる幻想的な光沢タイル。",
    imageUrl: "/blocks/uroko_tile.svg",
    material: "結晶片",
  },
  {
    name: "おうごんのカベ",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "壁",
    description: "まばゆい黄金の輝きを放つ豪華絢爛な壁ブロック。",
    imageUrl: "/blocks/ougon_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "おしゃれカベ・うえ",
    colorHex: "#B45309",
    colorName: "ブラウン",
    category: "壁",
    description: "上部に三角の木製飾りがついたエレガントな洋風白壁。",
    imageUrl: "/blocks/oshare_kabe_ue.svg",
    material: "木材",
  },
  {
    name: "おしゃれカベ・した",
    colorHex: "#B45309",
    colorName: "ブラウン",
    category: "壁",
    description: "下部に三角の木製飾りがついたエレガントな洋風白壁の土台。",
    imageUrl: "/blocks/oshare_kabe_shita.svg",
    material: "木材",
  },
  {
    name: "おしゃれカベ・まんなか",
    colorHex: "#B45309",
    colorName: "ブラウン",
    category: "壁",
    description: "中央にストライプ状の木枠が走るエレガントな洋風白壁。",
    imageUrl: "/blocks/oshare_kabe_mannaka.svg",
    material: "木材",
  },
  {
    name: "おしゃれタイル",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "床",
    description: "スカイブルーと白のフローラル幾何学文様が描かれた装飾タイル。",
    imageUrl: "/blocks/oshare_tile.svg",
    material: "結晶片",
  },
  {
    name: "おしゃれなおうごんのカベ",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "壁",
    description: "二重のスクエアレリーフと中央鋲が施された黄金の装飾壁。",
    imageUrl: "/blocks/osharena_ougon_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "おしゃれなてつのカベ",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "壁",
    description: "二重のスクエアレリーフと中央鋲が施されたスチールの装飾壁。",
    imageUrl: "/blocks/osharena_tetsu_no_kabe.svg",
    material: "石材",
  },
  {
    name: "おしゃれなブロンズのカベ",
    colorHex: "#D97706",
    colorName: "オレンジ",
    category: "壁",
    description: "二重のスクエアレリーフと中央鋲が施されたブロンズの装飾壁。",
    imageUrl: "/blocks/osharena_bronze_no_kabe.svg",
    material: "石材",
  },
  {
    name: "おしゃれボールもよう",
    colorHex: "#DB2777",
    colorName: "マゼンタ",
    category: "装飾",
    description: "深紅の地に金色のダマスク・ボール装飾が贅沢に織り込まれた壁。",
    imageUrl: "/blocks/oshare_ball_moyou.svg",
    material: "木材",
  },
  {
    name: "おしゃれゆかいし",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "床",
    description: "大小の方形切り石が美しく敷き詰められた石畳風の床ブロック。",
    imageUrl: "/blocks/oshare_yukaishi.svg",
    material: "石材",
  },
  {
    name: "おしゃれレンガ・うえ",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "壁",
    description: "上部にオレンジレンガの帯が入ったツートンの外壁ブロック。",
    imageUrl: "/blocks/oshare_renga_ue.svg",
    material: "石材",
  },
  {
    name: "おしゃれレンガ・した",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "壁",
    description: "下部にオレンジレンガの帯が入ったツートンの外壁ブロック。",
    imageUrl: "/blocks/oshare_renga_shita.svg",
    material: "石材",
  },
  {
    name: "おしゃれレンガ・まんなか",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "壁",
    description: "中央にオレンジレンガの帯が入ったツートンの外壁ブロック。",
    imageUrl: "/blocks/oshare_renga_mannaka.svg",
    material: "石材",
  },
  // --- 第2弾 49種 ---
  {
    name: "かいがらのつち",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "土",
    description: "細かな貝殻と青・緑の小粒が混ざり込んだ明るい砂土ブロック。",
    imageUrl: "/blocks/kaigara_no_tsuchi.svg",
    material: "砂",
  },
  {
    name: "かいがんのしばふ",
    colorHex: "#BEF264",
    colorName: "黄緑",
    category: "草",
    description: "潮風を浴びる海岸沿いに生える青々とした芝生土ブロック。",
    imageUrl: "/blocks/kaigan_no_shibafu.svg",
    material: "砂",
  },
  {
    name: "がけいわ",
    colorHex: "#F97316",
    colorName: "オレンジ",
    category: "石",
    description: "険しい崖の地層がくっきりと現れたオレンジ色の岩石ブロック。",
    imageUrl: "/blocks/gakeiwa.svg",
    material: "岩片",
  },
  {
    name: "かざんのいわ",
    colorHex: "#78350F",
    colorName: "パープル",
    category: "石",
    description: "マグマの熱で変色した暗紫色の重厚な火山岩ブロック。",
    imageUrl: "/blocks/kazan_no_iwa.svg",
    material: "石材",
  },
  {
    name: "かざんばい",
    colorHex: "#475569",
    colorName: "グレー",
    category: "石",
    description: "細かな火山灰が堆積して固まったダークグレーのブロック。",
    imageUrl: "/blocks/kazanbai.svg",
    material: "岩片",
  },
  {
    name: "からくさもよう",
    colorHex: "#86EFAC",
    colorName: "黄緑",
    category: "装飾",
    description: "淡い若草色に白の唐草文様が描かれた伝統的な装飾ブロック。",
    imageUrl: "/blocks/karakusa_moyou.svg",
    material: "結晶片",
  },
  {
    name: "カレーもよう",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "装飾",
    description: "美味しそうなカレー皿や野菜のイラストが描かれたユニークな装飾ブロック。",
    imageUrl: "/blocks/curry_moyou.svg",
    material: "木材",
  },
  {
    name: "きいろいいわ",
    colorHex: "#FACC15",
    colorName: "イエロー",
    category: "石",
    description: "硫黄や鉱物分を含んで明るい黄色を放つ自然岩石ブロック。",
    imageUrl: "/blocks/kiiroi_iwa.svg",
    material: "石材",
  },
  {
    name: "きいろいけずれたいわ",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "石",
    description: "風雨で削られて段差ができた黄色の岩石ブロック。",
    imageUrl: "/blocks/kiiroi_kezuretaiwa.svg",
    material: "石材",
  },
  {
    name: "キケンちたいのカベ",
    colorHex: "#EAB308",
    colorName: "ブラック",
    category: "壁",
    description: "黄色と黒の警戒斜めストライプが目を引くハザードウォールブロック。",
    imageUrl: "/blocks/kiken_chitai_no_kabe.svg",
    material: "石材",
  },
  {
    name: "ギザギザもよう",
    colorHex: "#06B6D4",
    colorName: "イエロー",
    category: "装飾",
    description: "鮮やかなシアンと黄・橙のジグザグ幾何学模様が施された装飾ブロック。",
    imageUrl: "/blocks/gizagiza_moyou.svg",
    material: "結晶片",
  },
  {
    name: "きのみのもよう",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "装飾",
    description: "色とりどりの果実や木の実がドット風に散りばめられた可愛らしいブロック。",
    imageUrl: "/blocks/kinomi_no_moyou.svg",
    material: "木材",
  },
  {
    name: "きゃくしつのカベ",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "壁",
    description: "清潔な白壁にミントブルーのツインラインが入ったホテルの客室風壁ブロック。",
    imageUrl: "/blocks/kyakushitsu_no_kabe.svg",
    material: "石材",
  },
  {
    name: "ギンガムチェック",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "装飾",
    description: "爽やかなスカイブルーと白の格子柄がかわいいギンガムチェックブロック。",
    imageUrl: "/blocks/gingham_check.svg",
    material: "木材",
  },
  {
    name: "クラッシュタイルのカベ",
    colorHex: "#F472B6",
    colorName: "マゼンタ",
    category: "壁",
    description: "ピンクや紫、橙のモザイク破片を敷き詰めた華やかなクラッシュタイル壁。",
    imageUrl: "/blocks/crash_tile_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "クリスタルのカベ",
    colorHex: "#22D3EE",
    colorName: "シアン",
    category: "壁",
    description: "光を反射して幾何学的に輝くクリスタルファセットが刻まれた結晶壁。",
    imageUrl: "/blocks/crystal_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "ぐるぐるもよう",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "装飾",
    description: "古代神殿やレトロ建築を想起させるオレンジの雷文・渦巻文様ブロック。",
    imageUrl: "/blocks/guruguru_moyou.svg",
    material: "石材",
  },
  {
    name: "グレーなマルのゆか",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "床",
    description: "中央に大きな円形モチーフが配置されたモダンなグレーの床ブロック。",
    imageUrl: "/blocks/gray_na_maru_no_yuka.svg",
    material: "石材",
  },
  {
    name: "くろいいわ",
    colorHex: "#27272A",
    colorName: "ブラック",
    category: "石",
    description: "光を吸い込むような漆黒の鉱物岩石ブロック。",
    imageUrl: "/blocks/kuroi_iwa.svg",
    material: "石材",
  },
  {
    name: "くろいツブがけいわ",
    colorHex: "#3F3F46",
    colorName: "ブラック",
    category: "石",
    description: "黒い岩肌に鉱物の小粒が埋め込まれた重厚な崖岩ブロック。",
    imageUrl: "/blocks/kuroi_tsubugakeiwa.svg",
    material: "石材",
  },
  {
    name: "くろがけいわ",
    colorHex: "#18181B",
    colorName: "ブラック",
    category: "石",
    description: "深い地底の断崖絶壁を構成する黒曜石質の崖岩ブロック。",
    imageUrl: "/blocks/kurogakeiwa.svg",
    material: "石材",
  },
  {
    name: "ごうかなじゅうたん",
    colorHex: "#DC2626",
    colorName: "レッド",
    category: "床",
    description: "鮮烈な赤地にゴールドの菱形紋様が刺繍された最高級絨毯ブロック。",
    imageUrl: "/blocks/gouka_na_juutan.svg",
    material: "木材",
  },
  {
    name: "こおり",
    colorHex: "#7DD3FC",
    colorName: "シアン",
    category: "特殊",
    description: "雪の結晶が浮かび上がる透き通ったひんやり冷たい氷ブロック。",
    imageUrl: "/blocks/koori.svg",
    material: "結晶片",
  },
  {
    name: "コケつち",
    colorHex: "#84CC16",
    colorName: "黄緑",
    category: "土",
    description: "しっとりとした深緑の苔が土壌全体を覆った自然味あふれるブロック。",
    imageUrl: "/blocks/koke_tsuchi.svg",
    material: "木材",
  },
  {
    name: "サイバーなゆか",
    colorHex: "#0284C7",
    colorName: "シアン",
    category: "床",
    description: "暗闇にネオンブルーの回路グリッドが発光するSF風サイバー床ブロック。",
    imageUrl: "/blocks/cyber_na_yuka.svg",
    material: "結晶片",
  },
  {
    name: "ザラザラいわ",
    colorHex: "#CBD5E1",
    colorName: "グレー",
    category: "石",
    description: "細かい砂粒のような手触りを持つライトグレーの砂岩系ブロック。",
    imageUrl: "/blocks/zarazara_iwa.svg",
    material: "石材",
  },
  {
    name: "ざらざらカベ",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "壁",
    description: "温かみのあるサンドイエローのザラザラした質感の外壁ブロック。",
    imageUrl: "/blocks/zarazara_kabe.svg",
    material: "砂",
  },
  {
    name: "ザラザラすなはま",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "土",
    description: "海岸のさらさらした細かい砂粒が敷き詰められた砂浜ブロック。",
    imageUrl: "/blocks/zarazara_sunahama.svg",
    material: "砂",
  },
  {
    name: "ザラザラのけずれたいわ",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "石",
    description: "ザラザラした質感のまま削り出された段差付きのグレー岩石ブロック。",
    imageUrl: "/blocks/zarazara_no_kezuretaiwa.svg",
    material: "石材",
  },
  {
    name: "さんがくのしばふ",
    colorHex: "#15803D",
    colorName: "グリーン",
    category: "草",
    description: "高山地帯の寒冷な気候に耐える濃い緑の山岳芝生ブロック。",
    imageUrl: "/blocks/sangaku_no_shibafu.svg",
    material: "木材",
  },
  {
    name: "さんかくもようのゆか",
    colorHex: "#F87171",
    colorName: "レッド",
    category: "床",
    description: "淡いピンクと白の三角形がパッチワーク状に並んだ幾何学床ブロック。",
    imageUrl: "/blocks/sankaku_moyou_no_yuka.svg",
    material: "石材",
  },
  {
    name: "しかくタイル",
    colorHex: "#FDE047",
    colorName: "ホワイト",
    category: "床",
    description: "清潔な白ベースの中央に四角いイエロータイルがはめ込まれた床ブロック。",
    imageUrl: "/blocks/shikaku_tile.svg",
    material: "石材",
  },
  {
    name: "しっくいのカベ",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "壁",
    description: "職人が丁寧に塗り上げた滑らかで真っ白な漆喰（しっくい）壁ブロック。",
    imageUrl: "/blocks/shikkui_no_kabe.svg",
    material: "石材",
  },
  {
    name: "しばふのゆか",
    colorHex: "#22C55E",
    colorName: "グリーン",
    category: "床",
    description: "庭園や屋上に敷き詰める手入れの行き届いたフラットな芝生床ブロック。",
    imageUrl: "/blocks/shibafu_no_yuka.svg",
    material: "木材",
  },
  {
    name: "シマシマのつち",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "土",
    description: "幾重もの鮮やかな赤褐色の地層が横縞となって現れた土壌ブロック。",
    imageUrl: "/blocks/shimashima_no_tsuchi.svg",
    material: "砂",
  },
  {
    name: "シャボンのもよう",
    colorHex: "#BAE6FD",
    colorName: "シアン",
    category: "装飾",
    description: "パステルカラーのシャボン玉がふわふわと浮かぶファンシーな装飾ブロック。",
    imageUrl: "/blocks/shabon_no_moyou.svg",
    material: "結晶片",
  },
  {
    name: "じゃり",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "土",
    description: "丸みを帯びた様々な色合いの小石が集まった砂利ブロック。",
    imageUrl: "/blocks/jari.svg",
    material: "岩片",
  },
  {
    name: "ショップのゆか",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "床",
    description: "明るい水色と白の縦ストライプが爽やかな店舗向けフロアブロック。",
    imageUrl: "/blocks/shop_no_yuka.svg",
    material: "石材",
  },
  {
    name: "しろいいわ",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "石",
    description: "純白の石灰分を豊富に含んだ清潔感あふれる白い自然岩ブロック。",
    imageUrl: "/blocks/shiroi_iwa.svg",
    material: "石材",
  },
  {
    name: "しろいけずれたいわ",
    colorHex: "#E2E8F0",
    colorName: "ホワイト",
    category: "石",
    description: "削り込まれた段差を持つ純白の彫刻用岩石ブロック。",
    imageUrl: "/blocks/shiroi_kezuretaiwa.svg",
    material: "石材",
  },
  {
    name: "シンプルしかくタイル",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "床",
    description: "均一な正方形の目地が刻まれた定番のホワイトタイルブロック。",
    imageUrl: "/blocks/simple_shikaku_tile.svg",
    material: "石材",
  },
  {
    name: "シンプルなゆか",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "床",
    description: "余計な装飾のないフラットで汎用性の高いプレーンな白床ブロック。",
    imageUrl: "/blocks/simple_na_yuka.svg",
    material: "石材",
  },
  {
    name: "スイーツなカベ・うえ",
    colorHex: "#F43F5E",
    colorName: "マゼンタ",
    category: "壁",
    description: "とろけるクリームの波形アイシングが施された甘いピンクの外壁上部。",
    imageUrl: "/blocks/sweets_kabe_ue.svg",
    material: "木材",
  },
  {
    name: "スイーツなカベ・した",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "壁",
    description: "星形・キャンディ型のデコレーションが散りばめられたパステルブルーの外壁下部。",
    imageUrl: "/blocks/sweets_kabe_shita.svg",
    material: "木材",
  },
  {
    name: "スイーツなカベ・まんなか",
    colorHex: "#F472B6",
    colorName: "マゼンタ",
    category: "壁",
    description: "ストロベリーキャンディの縦ストライプがかわいいスイーツ外壁中央。",
    imageUrl: "/blocks/sweets_kabe_mannaka.svg",
    material: "木材",
  },
  {
    name: "スクラップ",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "特殊",
    description: "金属片やワイヤー、廃材が圧縮されたインダストリアルなスクラップブロック。",
    imageUrl: "/blocks/scrap.svg",
    material: "石材",
  },
  {
    name: "すないわ",
    colorHex: "#FB923C",
    colorName: "オレンジ",
    category: "石",
    description: "砂漠地帯で風化したオレンジ色の硬質砂岩ブロック。",
    imageUrl: "/blocks/sunaiwa.svg",
    material: "砂",
  },
  {
    name: "せっかいせき",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "石",
    description: "なめらかなクリーム色をした良質な石灰石ブロック。",
    imageUrl: "/blocks/sekkaiseki.svg",
    material: "石材",
  },
  {
    name: "そうげんのしばふ",
    colorHex: "#84CC16",
    colorName: "黄緑",
    category: "草",
    description: "広大な草原に広がる柔らかな若草と肥沃な土壌の芝生ブロック。",
    imageUrl: "/blocks/sougen_no_shibafu.svg",
    material: "木材",
  },
  // --- バッチ3: 残り全公式カタログブロック（83種） ---
  {
    name: "木のカベ",
    colorHex: "#92400E",
    colorName: "ブラウン",
    category: "壁",
    description: "上質な木材を組み合わせた落ち着いた木目調の壁ブロック。",
    imageUrl: "/blocks/ki_no_kabe.svg",
    material: "木材",
  },
  {
    name: "木のカベ・ライト",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "壁",
    description: "明るい色合いの木材を用いたナチュラルな壁ブロック。",
    imageUrl: "/blocks/ki_no_kabe_light.svg",
    material: "木材",
  },
  {
    name: "ペンキぬりのカベ",
    colorHex: "#0284C7",
    colorName: "シアン",
    category: "壁",
    description: "爽やかなスカイブルーのペンキで塗装された滑らかな壁ブロック。",
    imageUrl: "/blocks/penkinuri_no_kabe.svg",
    material: "木材",
  },
  {
    name: "ぬののカベ",
    colorHex: "#F59E0B",
    colorName: "イエロー",
    category: "壁",
    description: "あたたかみのあるファブリック生地を張った装飾壁ブロック。",
    imageUrl: "/blocks/nuno_no_kabe.svg",
    material: "木材",
  },
  {
    name: "ほしぞらのカベ",
    colorHex: "#1E1B4B",
    colorName: "ネイビー",
    category: "壁",
    description: "満天の夜空と瞬く星々が描かれた神秘的な壁ブロック。",
    imageUrl: "/blocks/hoshizora_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "レザーのカベ",
    colorHex: "#78350F",
    colorName: "ブラウン",
    category: "壁",
    description: "高級感漂う本革の質感とステッチが施された壁ブロック。",
    imageUrl: "/blocks/leather_no_kabe.svg",
    material: "木材",
  },
  {
    name: "モダンなカベ",
    colorHex: "#475569",
    colorName: "グレー",
    category: "壁",
    description: "スレートグレーとアクセントガラスを配した現代風壁ブロック。",
    imageUrl: "/blocks/modern_na_kabe.svg",
    material: "石材",
  },
  {
    name: "レンガのカベ",
    colorHex: "#C2410C",
    colorName: "オレンジ",
    category: "壁",
    description: "赤レンガを丁寧に積み上げた重厚感のある壁ブロック。",
    imageUrl: "/blocks/renga_no_kabe.svg",
    material: "石材",
  },
  {
    name: "ふるびたいしカベ",
    colorHex: "#52525B",
    colorName: "グレー",
    category: "壁",
    description: "年月を経て風合いを増したアンティークな石造りの壁ブロック。",
    imageUrl: "/blocks/furubitai_ishikabe.svg",
    material: "石材",
  },
  {
    name: "ふるびたいしカベ・がら",
    colorHex: "#71717A",
    colorName: "グレー",
    category: "壁",
    description: "古の紋様が刻まれた歴史を感じさせる装飾石壁ブロック。",
    imageUrl: "/blocks/furubitai_ishikabe_gara.svg",
    material: "石材",
  },
  {
    name: "たてラインのカベ",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "壁",
    description: "スタイリッシュな縦ストライプのスリットが入った壁ブロック。",
    imageUrl: "/blocks/tateline_no_kabe.svg",
    material: "石材",
  },
  {
    name: "ブロンズのカベ",
    colorHex: "#92400E",
    colorName: "オレンジ",
    category: "壁",
    description: "青銅の重厚な輝きと質感を持つ金属壁ブロック。",
    imageUrl: "/blocks/bronze_no_kabe.svg",
    material: "岩片",
  },
  {
    name: "てつのカベ",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "壁",
    description: "堅牢な鉄板で覆われたインダストリアルな壁ブロック。",
    imageUrl: "/blocks/tetsu_no_kabe.svg",
    material: "岩片",
  },
  {
    name: "モンスターボールのカベ",
    colorHex: "#DC2626",
    colorName: "赤",
    category: "壁",
    description: "モンスターボールの象徴的なデザインが施された特別な壁ブロック。",
    imageUrl: "/blocks/monsterball_no_kabe.svg",
    material: "結晶片",
  },
  {
    name: "ライトアンティークカベ・うえ",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "壁",
    description: "クラシカルな装飾が上部に施された明るいアンティーク壁ブロック。",
    imageUrl: "/blocks/light_antique_kabe_ue.svg",
    material: "木材",
  },
  {
    name: "ライトアンティークカベ・なか",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "壁",
    description: "モールディングパネルが美しい明るいアンティーク壁ブロック。",
    imageUrl: "/blocks/light_antique_kabe_naka.svg",
    material: "木材",
  },
  {
    name: "ライトアンティークカベ・した",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "壁",
    description: "巾木と重厚な基部を持つ明るいアンティーク壁ブロック。",
    imageUrl: "/blocks/light_antique_kabe_shita.svg",
    material: "木材",
  },
  {
    name: "木のはしら・うえ",
    colorHex: "#B45309",
    colorName: "ブラウン",
    category: "壁",
    description: "柱頭の意匠が施された木製柱ブロックの上部パーツ。",
    imageUrl: "/blocks/ki_no_hashira_ue.svg",
    material: "木材",
  },
  {
    name: "木のはしら・まんなか",
    colorHex: "#92400E",
    colorName: "ブラウン",
    category: "壁",
    description: "すらりと伸びる直線美を持つ木製柱ブロックの中間パーツ。",
    imageUrl: "/blocks/ki_no_hashira_mannaka.svg",
    material: "木材",
  },
  {
    name: "木のはしら・した",
    colorHex: "#78350F",
    colorName: "ブラウン",
    category: "壁",
    description: "しっかりと大地を支える木製柱ブロックの基部パーツ。",
    imageUrl: "/blocks/ki_no_hashira_shita.svg",
    material: "木材",
  },
  {
    name: "ポップなカベ・うえ",
    colorHex: "#F472B6",
    colorName: "ピンク",
    category: "壁",
    description: "明るくポップなピンク色のカラーリングが特徴の壁上部ブロック。",
    imageUrl: "/blocks/pop_kabe_ue.svg",
    material: "木材",
  },
  {
    name: "ポップなカベ・まんなか",
    colorHex: "#EC4899",
    colorName: "ピンク",
    category: "壁",
    description: "黄色いドットモチーフが可愛らしいポップな壁中間ブロック。",
    imageUrl: "/blocks/pop_kabe_mannaka.svg",
    material: "木材",
  },
  {
    name: "ポップなカベ・した",
    colorHex: "#DB2777",
    colorName: "ピンク",
    category: "壁",
    description: "濃いピンクのラインがアクセントのポップな壁下部ブロック。",
    imageUrl: "/blocks/pop_kabe_shita.svg",
    material: "木材",
  },
  {
    name: "ポケセンのカベ・ふち",
    colorHex: "#DC2626",
    colorName: "赤",
    category: "壁",
    description: "ポケモンセンターのシンボルカラーである赤の縁取り壁ブロック。",
    imageUrl: "/blocks/pokecen_kabe_fuchi.svg",
    material: "石材",
  },
  {
    name: "ポケセンのカベ・うえ",
    colorHex: "#FFFFFF",
    colorName: "ホワイト",
    category: "壁",
    description: "ポケモンセンターの明るい白壁に赤いラインが入った上部ブロック。",
    imageUrl: "/blocks/pokecen_kabe_ue.svg",
    material: "石材",
  },
  {
    name: "ポケセンのカベ・まんなか",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "壁",
    description: "清潔感あふれるポケモンセンターの白い壁中間ブロック。",
    imageUrl: "/blocks/pokecen_kabe_mannaka.svg",
    material: "石材",
  },
  {
    name: "ポケセンのカベ・した",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "壁",
    description: "青いアクセントラインが走るポケモンセンターの壁下部ブロック。",
    imageUrl: "/blocks/pokecen_kabe_shita.svg",
    material: "石材",
  },
  {
    name: "木のゆか",
    colorHex: "#B45309",
    colorName: "ブラウン",
    category: "床",
    description: "温かみのある木の板を並べたスタンダードなフローリングブロック。",
    imageUrl: "/blocks/ki_no_yuka.svg",
    material: "木材",
  },
  {
    name: "ななめの木のゆか",
    colorHex: "#92400E",
    colorName: "ブラウン",
    category: "床",
    description: "斜め貼りの木目がリズミカルな空間を演出する床ブロック。",
    imageUrl: "/blocks/naname_ki_no_yuka.svg",
    material: "木材",
  },
  {
    name: "タテヨコの木のゆか",
    colorHex: "#D97706",
    colorName: "ブラウン",
    category: "床",
    description: "市松模様のように縦横交互に組まれた寄木床ブロック。",
    imageUrl: "/blocks/tateyoko_ki_no_yuka.svg",
    material: "木材",
  },
  {
    name: "フローリングのゆか",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "床",
    description: "明るいオーク材のような質感を持つ洗練された床ブロック。",
    imageUrl: "/blocks/flooring_no_yuka.svg",
    material: "木材",
  },
  {
    name: "モダンなカーペット",
    colorHex: "#475569",
    colorName: "グレー",
    category: "床",
    description: "シックなダークグレーと幾何学模様の上質なカーペット床。",
    imageUrl: "/blocks/modern_na_carpet.svg",
    material: "木材",
  },
  {
    name: "タイルカーペット",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "床",
    description: "オフィスや商業施設に最適な防音性に優れたタイルカーペット。",
    imageUrl: "/blocks/tile_carpet.svg",
    material: "木材",
  },
  {
    name: "わたのゆか",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "床",
    description: "ふんわりとした綿のようなやわらかい踏み心地の白い床ブロック。",
    imageUrl: "/blocks/wata_no_yuka.svg",
    material: "木材",
  },
  {
    name: "フカフカじゅうたん",
    colorHex: "#DC2626",
    colorName: "赤",
    category: "床",
    description: "深い赤色と贅沢な毛足を持つフカフカの絨毯ブロック。",
    imageUrl: "/blocks/fukafuka_juutan.svg",
    material: "木材",
  },
  {
    name: "たたみ",
    colorHex: "#A3E635",
    colorName: "緑",
    category: "床",
    description: "い草の爽やかな香りと美しいヘリを持つ和室の畳ブロック。",
    imageUrl: "/blocks/tatami.svg",
    material: "木材",
  },
  {
    name: "フェルトマット",
    colorHex: "#10B981",
    colorName: "緑",
    category: "床",
    description: "滑らかなエメラルドグリーンの質感が心地よいフェルト床。",
    imageUrl: "/blocks/felt_mat.svg",
    material: "木材",
  },
  {
    name: "木のフカフカはしら",
    colorHex: "#CA8A04",
    colorName: "イエロー",
    category: "壁",
    description: "木製フレームに柔らかなクッション素材を巻き付けた柱ブロック。",
    imageUrl: "/blocks/ki_no_fukafuka_hashira.svg",
    material: "木材",
  },
  {
    name: "だいりせき",
    colorHex: "#F1F5F9",
    colorName: "ホワイト",
    category: "石",
    description: "美しいマーブル模様が浮かぶ最高級の白い大理石ブロック。",
    imageUrl: "/blocks/dairiseki.svg",
    material: "石材",
  },
  {
    name: "だいりせきのゆか・ダーク",
    colorHex: "#334155",
    colorName: "グレー",
    category: "床",
    description: "光沢のある漆黒のマーブル模様が高級感を放つダーク大理石床。",
    imageUrl: "/blocks/dairiseki_yuka_dark.svg",
    material: "石材",
  },
  {
    name: "だいりせきのゆか・ライト",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "床",
    description: "明るい光を反射する純白の鏡面仕上げ大理石床ブロック。",
    imageUrl: "/blocks/dairiseki_yuka_light.svg",
    material: "石材",
  },
  {
    name: "ふるびたいしゆか",
    colorHex: "#71717A",
    colorName: "グレー",
    category: "床",
    description: "石畳の風合いが歴史を感じさせるアンティークな床ブロック。",
    imageUrl: "/blocks/furubitai_ishiyuka.svg",
    material: "石材",
  },
  {
    name: "ろっかくけいのゆか",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "床",
    description: "ハニカム構造の六角形タイルが規則正しく並んだ幾何学床。",
    imageUrl: "/blocks/rokkakukei_no_yuka.svg",
    material: "石材",
  },
  {
    name: "てっぱんのゆか",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "床",
    description: "滑り止めのエンボス加工が施された重工業用鉄板床ブロック。",
    imageUrl: "/blocks/teppan_no_yuka.svg",
    material: "岩片",
  },
  {
    name: "てつのタイル",
    colorHex: "#475569",
    colorName: "グレー",
    category: "床",
    description: "金属プレートを整然と敷き詰めた頑強なスチールタイル床。",
    imageUrl: "/blocks/tetsu_no_tile.svg",
    material: "岩片",
  },
  {
    name: "ネオンなゆか",
    colorHex: "#06B6D4",
    colorName: "シアン",
    category: "床",
    description: "サイバーパンクな発光ラインが暗闇で輝くネオン床ブロック。",
    imageUrl: "/blocks/neon_na_yuka.svg",
    material: "結晶片",
  },
  {
    name: "モザイクタイル",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "床",
    description: "色とりどりの小さなガラス片を組み合わせたモザイク装飾床。",
    imageUrl: "/blocks/mosaic_tile.svg",
    material: "石材",
  },
  {
    name: "レンガのゆか",
    colorHex: "#C2410C",
    colorName: "オレンジ",
    category: "床",
    description: "舗装された赤レンガの温かみあるアプローチ床ブロック。",
    imageUrl: "/blocks/renga_no_yuka.svg",
    material: "石材",
  },
  {
    name: "はくせんのみち・よこ",
    colorHex: "#334155",
    colorName: "グレー",
    category: "床",
    description: "道路の白線が横方向に引かれたアスファルト舗装路ブロック。",
    imageUrl: "/blocks/hakusen_no_michi_yoko.svg",
    material: "石材",
  },
  {
    name: "はくせんのみち・たて",
    colorHex: "#334155",
    colorName: "グレー",
    category: "床",
    description: "道路の白線が縦方向に引かれたアスファルト舗装路ブロック。",
    imageUrl: "/blocks/hakusen_no_michi_tate.svg",
    material: "石材",
  },
  {
    name: "つみあげわら",
    colorHex: "#EAB308",
    colorName: "イエロー",
    category: "装飾",
    description: "収穫した稲わらを束ねて高く積み上げたカントリー調ブロック。",
    imageUrl: "/blocks/tsumiagewara.svg",
    material: "木材",
  },
  {
    name: "てっぱん",
    colorHex: "#64748B",
    colorName: "グレー",
    category: "装飾",
    description: "分厚い圧延鋼板でできた重厚なインダストリアルブロック。",
    imageUrl: "/blocks/teppan.svg",
    material: "岩片",
  },
  {
    name: "ブロックライト",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "装飾",
    description: "全体が優しく発光し周囲を照らす照明ブロック。",
    imageUrl: "/blocks/block_light.svg",
    material: "結晶片",
  },
  {
    name: "ていぼう",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "装飾",
    description: "波や風を防ぐために設計された強固なコンクリート堤防ブロック。",
    imageUrl: "/blocks/teibou.svg",
    material: "石材",
  },
  {
    name: "みずたまもよう",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "装飾",
    description: "爽やかなスカイブルー地に白い水玉が弾けるキュートな装飾壁。",
    imageUrl: "/blocks/mizutama_moyou.svg",
    material: "木材",
  },
  {
    name: "たてストライプ",
    colorHex: "#22C55E",
    colorName: "緑",
    category: "装飾",
    description: "鮮やかなグリーンとホワイトの縦縞模様が爽やかな装飾壁。",
    imageUrl: "/blocks/tate_stripe.svg",
    material: "木材",
  },
  {
    name: "よこストライプ",
    colorHex: "#22C55E",
    colorName: "緑",
    category: "装飾",
    description: "ボーダーラインが部屋に広がりを与えるグリーンの横縞装飾壁。",
    imageUrl: "/blocks/yoko_stripe.svg",
    material: "木材",
  },
  {
    name: "タータンチェック",
    colorHex: "#DC2626",
    colorName: "赤",
    category: "装飾",
    description: "スコットランド伝統の気品ある赤系タータンチェック模様壁。",
    imageUrl: "/blocks/tartan_check.svg",
    material: "木材",
  },
  {
    name: "ボールもよう",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "装飾",
    description: "ポップなモンスターボールのアイコンが整列した装飾ブロック。",
    imageUrl: "/blocks/ball_moyou.svg",
    material: "結晶片",
  },
  {
    name: "ちどりごうし",
    colorHex: "#F8FAFC",
    colorName: "グレー",
    category: "装飾",
    description: "伝統的な千鳥格子（ハウンドトゥース）が織りなす格調高い壁。",
    imageUrl: "/blocks/chidorigoshi.svg",
    material: "木材",
  },
  {
    name: "ふゆのもよう",
    colorHex: "#38BDF8",
    colorName: "シアン",
    category: "装飾",
    description: "結晶化する雪の華と冬景色をモチーフにした美しい装飾ブロック。",
    imageUrl: "/blocks/fuyu_no_moyou.svg",
    material: "結晶片",
  },
  {
    name: "はっぱもよう",
    colorHex: "#4ADE80",
    colorName: "緑",
    category: "装飾",
    description: "瑞々しい木の葉が生き生きと描かれたボタニカル装飾ブロック。",
    imageUrl: "/blocks/happa_moyou.svg",
    material: "木材",
  },
  {
    name: "はなもよう",
    colorHex: "#F472B6",
    colorName: "ピンク",
    category: "装飾",
    description: "可憐な花々が咲き誇る華やかで明るい装飾ブロック。",
    imageUrl: "/blocks/hana_moyou.svg",
    material: "木材",
  },
  {
    name: "ほしのもよう",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "装飾",
    description: "夜空に瞬く金色の星屑が散りばめられたドリーミーな装飾壁。",
    imageUrl: "/blocks/hoshi_no_moyou.svg",
    material: "結晶片",
  },
  {
    name: "てんくうのしばふ",
    colorHex: "#34D399",
    colorName: "緑",
    category: "草",
    description: "天空の浮島に自生する清らかな光を帯びた芝生ブロック。",
    imageUrl: "/blocks/tenkuu_no_shibafu.svg",
    material: "木材",
  },
  {
    name: "ふつうのつち",
    colorHex: "#854D0E",
    colorName: "ブラウン",
    category: "土",
    description: "肥沃で植物の育成に適した自然の土ブロック。",
    imageUrl: "/blocks/futsuu_no_tsuchi.svg",
    material: "砂",
  },
  {
    name: "まっしろなつち",
    colorHex: "#F8FAFC",
    colorName: "ホワイト",
    category: "土",
    description: "鉱物粒子を含んだ白砂のように美しい純白の土ブロック。",
    imageUrl: "/blocks/masshiro_na_tsuchi.svg",
    material: "砂",
  },
  {
    name: "ふつうのすな",
    colorHex: "#FDE047",
    colorName: "イエロー",
    category: "土",
    description: "さらさらとした手触りのきめ細かい砂ブロック。",
    imageUrl: "/blocks/futsuu_no_suna.svg",
    material: "砂",
  },
  {
    name: "ツブがけいわ",
    colorHex: "#EA580C",
    colorName: "オレンジ",
    category: "石",
    description: "粗い鉱物粒がぎっしり詰まった赤褐色の断崖岩ブロック。",
    imageUrl: "/blocks/tsubugakeiwa.svg",
    material: "石材",
  },
  {
    name: "マグマいわ",
    colorHex: "#7F1D1D",
    colorName: "赤",
    category: "石",
    description: "内部に熱いマグマの脈が脈動する超高温の火山岩ブロック。",
    imageUrl: "/blocks/magmaiwa.svg",
    material: "岩片",
  },
  {
    name: "どうくつのいわ",
    colorHex: "#334155",
    colorName: "グレー",
    category: "石",
    description: "深い地底洞窟の冷気と湿度に包まれた硬質な岩石ブロック。",
    imageUrl: "/blocks/doukutsu_no_iwa.svg",
    material: "石材",
  },
  {
    name: "どうこうせき(パサパサ)",
    colorHex: "#EA580C",
    colorName: "オレンジ",
    category: "石",
    description: "パサパサこうやで採掘される銅の鉱脈を含んだ岩石ブロック。",
    imageUrl: "/blocks/doukouseki_pasapasa.svg",
    material: "岩片",
  },
  {
    name: "どうこうせき(ドンヨリ)",
    colorHex: "#EA580C",
    colorName: "オレンジ",
    category: "石",
    description: "ドンヨリうみべで採掘される湿潤な環境の銅鉱石ブロック。",
    imageUrl: "/blocks/doukouseki_donyori.svg",
    material: "岩片",
  },
  {
    name: "どうこうせき(ゴツゴツ)",
    colorHex: "#EA580C",
    colorName: "オレンジ",
    category: "石",
    description: "ゴツゴツやまの険しい岩肌から採れる良質な銅鉱石ブロック。",
    imageUrl: "/blocks/doukouseki_gotsugotsu.svg",
    material: "岩片",
  },
  {
    name: "どうこうせき(キラキラ)",
    colorHex: "#EA580C",
    colorName: "オレンジ",
    category: "石",
    description: "キラキラうきしまの澄んだ結晶中に埋まる高純度の銅鉱石。",
    imageUrl: "/blocks/doukouseki_kirakira.svg",
    material: "岩片",
  },
  {
    name: "てっこうせき",
    colorHex: "#CBD5E1",
    colorName: "グレー",
    category: "石",
    description: "銀白色の鉄成分を豊富に含んだ頑丈な鉄鉱石ブロック。",
    imageUrl: "/blocks/tekkouseki.svg",
    material: "岩片",
  },
  {
    name: "ポケメタルこうせき",
    colorHex: "#EC4899",
    colorName: "マゼンタ",
    category: "石",
    description: "未知の超エネルギーを秘めた虹色に輝く希少メタル鉱石。",
    imageUrl: "/blocks/pokemetal_kouseki.svg",
    material: "結晶片",
  },
  {
    name: "ヒカリいし",
    colorHex: "#FEF08A",
    colorName: "イエロー",
    category: "石",
    description: "太陽の光を蓄えて夜間に暖かな黄金の光を放つ奇跡の石。",
    imageUrl: "/blocks/hikari_ishi.svg",
    material: "結晶片",
  },
  {
    name: "ナゾのいし",
    colorHex: "#A855F7",
    colorName: "紫",
    category: "石",
    description: "深紫の妖しいオーラをまとう古代の神秘的な鉱石ブロック。",
    imageUrl: "/blocks/nazo_no_ishi.svg",
    material: "結晶片",
  },
  {
    name: "ひびわれすないわ",
    colorHex: "#CA8A04",
    colorName: "イエロー",
    category: "石",
    description: "乾燥と日照りによって幾重にもひび割れた砂岩ブロック。",
    imageUrl: "/blocks/hibiware_sunaiwa.svg",
    material: "砂",
  },
  {
    name: "ねんど",
    colorHex: "#94A3B8",
    colorName: "グレー",
    category: "土",
    description: "粘り気が強く加工性に優れたきめ細かな粘土ブロック。",
    imageUrl: "/blocks/nendo.svg",
    material: "砂",
  },
  {
    name: "きんこうせき",
    colorHex: "#FACC15",
    colorName: "イエロー",
    category: "石",
    description: "眩い黄金の輝きを放つ極めて希少価値の高い金鉱石ブロック。",
    imageUrl: "/blocks/kinkouseki.svg",
    material: "結晶片",
  },
  {
    name: "メタモンだらけもよう",
    colorHex: "#C084FC",
    colorName: "紫",
    category: "装飾",
    description: "愛嬌たっぷりのへんしんポケモン・メタモンが一面に描かれた限定壁。",
    imageUrl: "/blocks/metamon_darake_moyou.svg",
    material: "結晶片",
  },
];

function seedMemoryStore() {
  memStore.blocks.clear();
  memStore.blockMaterials.length = 0;
  memStore.miningLocations.clear();
  memStore.materials.clear();

  const now = new Date();
  const locationIds = new Map<string, number>();

  for (const loc of starterLocations) {
    const id = memStore.nextId.miningLocation++;
    memStore.miningLocations.set(id, {
      id,
      name: loc.name,
      description: loc.description,
      imageUrl: null,
      createdAt: now,
      updatedAt: now,
    });
    locationIds.set(loc.name, id);
  }

  const materialIds = new Map<string, number>();
  for (const mat of starterMaterials) {
    const id = memStore.nextId.material++;
    memStore.materials.set(id, {
      id,
      name: mat.name,
      description: mat.description,
      imageUrl: null,
      miningLocationId: locationIds.get(mat.location) ?? null,
      createdAt: now,
      updatedAt: now,
    });
    materialIds.set(mat.name, id);
  }

  for (const sp of specialCatalogBlocks) {
    const blockId = memStore.nextId.block++;
    memStore.blocks.set(blockId, {
      id: blockId,
      name: sp.name,
      colorHex: sp.colorHex,
      colorName: sp.colorName,
      category: sp.category,
      description: sp.description,
      imageUrl: sp.imageUrl,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    const matId = materialIds.get(sp.material) ?? materialIds.get("石材");
    if (matId) {
      memStore.blockMaterials.push({
        id: memStore.nextId.blockMaterial++,
        blockId,
        materialId: matId,
        quantity: 1,
      });
    }
  }
}

/** 公式画像ブロックをDBおよびメモリに登録・同期し、架空ブロックをすべて削除する。 */
export async function ensureCatalogSeeded() {
  seedMemoryStore();

  const db = await getDb();
  if (!db) return;

  try {
    // 1. Ensure locations & materials exist
    const existingLocations = await db.select().from(miningLocations);
    if (existingLocations.length === 0) {
      await db.insert(miningLocations).values(starterLocations);
    }
    const storedLocations = await db.select().from(miningLocations);
    const locationIds = new Map(storedLocations.map(l => [l.name, l.id]));

    const existingMaterials = await db.select().from(materials);
    const existingMatNames = new Set(existingMaterials.map(m => m.name));
    const missingMaterials = starterMaterials.filter(m => !existingMatNames.has(m.name));
    if (missingMaterials.length > 0) {
      await db.insert(materials).values(missingMaterials.map(m => ({
        name: m.name,
        description: m.description,
        miningLocationId: locationIds.get(m.location) ?? null,
      })));
    }
    const storedMaterials = await db.select().from(materials);
    const materialIds = new Map(storedMaterials.map(m => [m.name, m.id]));

    // 2. Clean up imaginary blocks (blocks not in the official catalog)
    const officialNames = new Set(specialCatalogBlocks.map(sp => sp.name));
    const allDbBlocks = await db.select().from(blocks);
    const imaginaryBlockIds = allDbBlocks
      .filter(b => !b.imageUrl || b.imageUrl.trim() === "" || !officialNames.has(b.name))
      .map(b => b.id);

    if (imaginaryBlockIds.length > 0) {
      await db.delete(blockMaterials).where(inArray(blockMaterials.blockId, imaginaryBlockIds));

      const firstOfficial = allDbBlocks.find(b => officialNames.has(b.name));
      if (firstOfficial) {
        await db.update(projectSelections)
          .set({ selectedBlockId: firstOfficial.id })
          .where(inArray(projectSelections.selectedBlockId, imaginaryBlockIds));
      }

      await db.delete(blocks).where(inArray(blocks.id, imaginaryBlockIds));
      console.log(`[CatalogSeed] Cleaned up ${imaginaryBlockIds.length} imaginary blocks from database.`);
    }

    // 3. Ensure all official blocks are in DB with correct images
    const currentDbBlocks = await db.select().from(blocks);
    const currentMap = new Map(currentDbBlocks.map(b => [b.name, b]));

    for (const sp of specialCatalogBlocks) {
      const existing = currentMap.get(sp.name);
      if (!existing) {
        const [inserted] = await db.insert(blocks).values({
          name: sp.name,
          colorHex: sp.colorHex,
          colorName: sp.colorName,
          category: sp.category,
          description: sp.description,
          imageUrl: sp.imageUrl,
          isActive: true,
        });
        const insertResult = inserted as any;
        const newBlockId = insertResult?.insertId ?? insertResult?.[0]?.insertId;
        const matId = materialIds.get(sp.material) ?? materialIds.get("石材");
        if (matId && newBlockId) {
          await db.insert(blockMaterials).values({
            blockId: Number(newBlockId),
            materialId: matId,
            quantity: 1,
          });
        }
      } else {
        if (existing.imageUrl !== sp.imageUrl || existing.colorHex !== sp.colorHex) {
          await db.update(blocks).set({
            imageUrl: sp.imageUrl,
            colorHex: sp.colorHex,
            colorName: sp.colorName,
            category: sp.category,
            description: sp.description,
            isActive: true,
          }).where(eq(blocks.id, existing.id));
        }
      }
    }

    // Ensure all blocks have material associations
    const finalBlocks = await db.select().from(blocks);
    const existingBlockMaterials = await db.select().from(blockMaterials);
    const blockMatSet = new Set(existingBlockMaterials.map(bm => `${bm.blockId}-${bm.materialId}`));

    const missingBlockMats: { blockId: number; materialId: number; quantity: number }[] = [];
    for (const b of finalBlocks) {
      const sp = specialCatalogBlocks.find(s => s.name === b.name);
      if (sp) {
        const matId = materialIds.get(sp.material) ?? materialIds.get("石材");
        if (matId && !blockMatSet.has(`${b.id}-${matId}`)) {
          missingBlockMats.push({ blockId: b.id, materialId: matId, quantity: 1 });
        }
      }
    }
    if (missingBlockMats.length > 0) {
      await db.insert(blockMaterials).values(missingBlockMats);
    }
  } catch (err) {
    console.warn("[CatalogSeed] Database sync error, using memory store:", err);
  }
}

export async function getBlockById(id: number) {
  const db = await getDb();
  if (db) {
    try {
      const result = await db.select().from(blocks).where(eq(blocks.id, id)).limit(1);
      if (result[0]) return result[0];
    } catch {
      // fallback to memory
    }
  }
  return memStore.blocks.get(id);
}
